// Autogenerated from Pigeon (v26.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsSecureContentApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsSecureContentApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsSecureContentApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashSecureContentApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashSecureContentApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashSecureContentApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct ProtectionConfig: Hashable {
  var enabled: Bool
  var protectInAppSwitcher: Bool
  var appSwitcherColor: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProtectionConfig? {
    let enabled = pigeonVar_list[0] as! Bool
    let protectInAppSwitcher = pigeonVar_list[1] as! Bool
    let appSwitcherColor = pigeonVar_list[2] as! Int64

    return ProtectionConfig(
      enabled: enabled,
      protectInAppSwitcher: protectInAppSwitcher,
      appSwitcherColor: appSwitcherColor
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      protectInAppSwitcher,
      appSwitcherColor,
    ]
  }
  static func == (lhs: ProtectionConfig, rhs: ProtectionConfig) -> Bool {
    return deepEqualsSecureContentApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashSecureContentApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SecureEvent: Hashable {
  var type: String
  var platform: String
  var timestamp: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SecureEvent? {
    let type = pigeonVar_list[0] as! String
    let platform = pigeonVar_list[1] as! String
    let timestamp: String? = nilOrValue(pigeonVar_list[2])

    return SecureEvent(
      type: type,
      platform: platform,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      platform,
      timestamp,
    ]
  }
  static func == (lhs: SecureEvent, rhs: SecureEvent) -> Bool {
    return deepEqualsSecureContentApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashSecureContentApi(value: toList(), hasher: &hasher)
  }
}

private class SecureContentApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ProtectionConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return SecureEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SecureContentApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ProtectionConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SecureEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SecureContentApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SecureContentApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SecureContentApiPigeonCodecWriter(data: data)
  }
}

class SecureContentApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SecureContentApiPigeonCodec(readerWriter: SecureContentApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureContentHostApi {
  func configureProtection(config: ProtectionConfig) throws
  func isScreenCaptured() throws -> Bool
  func requestBiometricAuth(reason: String) throws
  func checkIntegrity() throws
  func setSensitiveClipboard(content: String, clearAfterMs: Int64) throws
  func clearSensitiveClipboard() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureContentHostApiSetup {
  static var codec: FlutterStandardMessageCodec { SecureContentApiPigeonCodec.shared }
  /// Sets up an instance of `SecureContentHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureContentHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureProtectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.configureProtection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureProtectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ProtectionConfig
        do {
          try api.configureProtection(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureProtectionChannel.setMessageHandler(nil)
    }
    let isScreenCapturedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.isScreenCaptured\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScreenCapturedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isScreenCaptured()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isScreenCapturedChannel.setMessageHandler(nil)
    }
    let requestBiometricAuthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.requestBiometricAuth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestBiometricAuthChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        do {
          try api.requestBiometricAuth(reason: reasonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestBiometricAuthChannel.setMessageHandler(nil)
    }
    let checkIntegrityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.checkIntegrity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkIntegrityChannel.setMessageHandler { _, reply in
        do {
          try api.checkIntegrity()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkIntegrityChannel.setMessageHandler(nil)
    }
    let setSensitiveClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.setSensitiveClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSensitiveClipboardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contentArg = args[0] as! String
        let clearAfterMsArg = args[1] as! Int64
        do {
          try api.setSensitiveClipboard(content: contentArg, clearAfterMs: clearAfterMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSensitiveClipboardChannel.setMessageHandler(nil)
    }
    let clearSensitiveClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.clearSensitiveClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSensitiveClipboardChannel.setMessageHandler { _, reply in
        do {
          try api.clearSensitiveClipboard()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSensitiveClipboardChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SecureContentFlutterApiProtocol {
  func onEvent(event eventArg: SecureEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SecureContentFlutterApi: SecureContentFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SecureContentApiPigeonCodec {
    return SecureContentApiPigeonCodec.shared
  }
  func onEvent(event eventArg: SecureEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.secure_content.SecureContentFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
