plugins {
    id "com.android.library"
}

group 'com.codenameakshay.secure_content'
version '2.0-SNAPSHOT'

dependencies {
    implementation 'androidx.biometric:biometric:1.1.0'
}

android {
    namespace "com.codenameakshay.secure_content"
    compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 23
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}
