// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum SecureContentApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct ProtectionConfig: Hashable, CustomStringConvertible {
  var enabled: Bool
  var protectInAppSwitcher: Bool
  var appSwitcherColor: Int64
  /// Optional name of an image in the host app's native asset catalog to
  /// center on the app-switcher / privacy overlay (rendered as a template,
  /// tinted to contrast the background). When null the overlay is a plain fill.
  var appSwitcherImageName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProtectionConfig? {
    let enabled = pigeonVar_list[0] as! Bool
    let protectInAppSwitcher = pigeonVar_list[1] as! Bool
    let appSwitcherColor = pigeonVar_list[2] as! Int64
    let appSwitcherImageName: String? = nilOrValue(pigeonVar_list[3])

    return ProtectionConfig(
      enabled: enabled,
      protectInAppSwitcher: protectInAppSwitcher,
      appSwitcherColor: appSwitcherColor,
      appSwitcherImageName: appSwitcherImageName
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      protectInAppSwitcher,
      appSwitcherColor,
      appSwitcherImageName,
    ]
  }
  static func == (lhs: ProtectionConfig, rhs: ProtectionConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SecureContentApiPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && SecureContentApiPigeonInternal.deepEquals(lhs.protectInAppSwitcher, rhs.protectInAppSwitcher) && SecureContentApiPigeonInternal.deepEquals(lhs.appSwitcherColor, rhs.appSwitcherColor) && SecureContentApiPigeonInternal.deepEquals(lhs.appSwitcherImageName, rhs.appSwitcherImageName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProtectionConfig")
    SecureContentApiPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    SecureContentApiPigeonInternal.deepHash(value: protectInAppSwitcher, hasher: &hasher)
    SecureContentApiPigeonInternal.deepHash(value: appSwitcherColor, hasher: &hasher)
    SecureContentApiPigeonInternal.deepHash(value: appSwitcherImageName, hasher: &hasher)
  }

  public var description: String {
    return "ProtectionConfig(enabled: \(String(describing: enabled)), protectInAppSwitcher: \(String(describing: protectInAppSwitcher)), appSwitcherColor: \(String(describing: appSwitcherColor)), appSwitcherImageName: \(String(describing: appSwitcherImageName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SecureEvent: Hashable, CustomStringConvertible {
  var type: String
  var platform: String
  var timestamp: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SecureEvent? {
    let type = pigeonVar_list[0] as! String
    let platform = pigeonVar_list[1] as! String
    let timestamp: String? = nilOrValue(pigeonVar_list[2])

    return SecureEvent(
      type: type,
      platform: platform,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      platform,
      timestamp,
    ]
  }
  static func == (lhs: SecureEvent, rhs: SecureEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SecureContentApiPigeonInternal.deepEquals(lhs.type, rhs.type) && SecureContentApiPigeonInternal.deepEquals(lhs.platform, rhs.platform) && SecureContentApiPigeonInternal.deepEquals(lhs.timestamp, rhs.timestamp)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SecureEvent")
    SecureContentApiPigeonInternal.deepHash(value: type, hasher: &hasher)
    SecureContentApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
    SecureContentApiPigeonInternal.deepHash(value: timestamp, hasher: &hasher)
  }

  public var description: String {
    return "SecureEvent(type: \(String(describing: type)), platform: \(String(describing: platform)), timestamp: \(String(describing: timestamp)))"
  }
}

private class SecureContentApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ProtectionConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return SecureEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SecureContentApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ProtectionConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SecureEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SecureContentApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SecureContentApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SecureContentApiPigeonCodecWriter(data: data)
  }
}

class SecureContentApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SecureContentApiPigeonCodec(readerWriter: SecureContentApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureContentHostApi {
  func configureProtection(config: ProtectionConfig) throws
  func isScreenCaptured() throws -> Bool
  func requestBiometricAuth(reason: String) throws
  func checkIntegrity() throws
  func setSensitiveClipboard(content: String, clearAfterMs: Int64) throws
  func clearSensitiveClipboard() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureContentHostApiSetup {
  static var codec: FlutterStandardMessageCodec { SecureContentApiPigeonCodec.shared }
  /// Sets up an instance of `SecureContentHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureContentHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureProtectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.configureProtection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureProtectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ProtectionConfig
        do {
          try api.configureProtection(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureProtectionChannel.setMessageHandler(nil)
    }
    let isScreenCapturedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.isScreenCaptured\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScreenCapturedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isScreenCaptured()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isScreenCapturedChannel.setMessageHandler(nil)
    }
    let requestBiometricAuthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.requestBiometricAuth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestBiometricAuthChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        do {
          try api.requestBiometricAuth(reason: reasonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestBiometricAuthChannel.setMessageHandler(nil)
    }
    let checkIntegrityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.checkIntegrity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkIntegrityChannel.setMessageHandler { _, reply in
        do {
          try api.checkIntegrity()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkIntegrityChannel.setMessageHandler(nil)
    }
    let setSensitiveClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.setSensitiveClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSensitiveClipboardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contentArg = args[0] as! String
        let clearAfterMsArg = args[1] as! Int64
        do {
          try api.setSensitiveClipboard(content: contentArg, clearAfterMs: clearAfterMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSensitiveClipboardChannel.setMessageHandler(nil)
    }
    let clearSensitiveClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_content.SecureContentHostApi.clearSensitiveClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSensitiveClipboardChannel.setMessageHandler { _, reply in
        do {
          try api.clearSensitiveClipboard()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSensitiveClipboardChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SecureContentFlutterApiProtocol {
  func onEvent(event eventArg: SecureEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SecureContentFlutterApi: SecureContentFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SecureContentApiPigeonCodec {
    return SecureContentApiPigeonCodec.shared
  }
  func onEvent(event eventArg: SecureEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.secure_content.SecureContentFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
