// Autogenerated from Pigeon (v26.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.codenameakshay.secure_content.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SecureContentApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ProtectionConfig (
  val enabled: Boolean,
  val protectInAppSwitcher: Boolean,
  val appSwitcherColor: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProtectionConfig {
      val enabled = pigeonVar_list[0] as Boolean
      val protectInAppSwitcher = pigeonVar_list[1] as Boolean
      val appSwitcherColor = pigeonVar_list[2] as Long
      return ProtectionConfig(enabled, protectInAppSwitcher, appSwitcherColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      protectInAppSwitcher,
      appSwitcherColor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ProtectionConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return SecureContentApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SecureEvent (
  val type: String,
  val platform: String,
  val timestamp: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SecureEvent {
      val type = pigeonVar_list[0] as String
      val platform = pigeonVar_list[1] as String
      val timestamp = pigeonVar_list[2] as String?
      return SecureEvent(type, platform, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      platform,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SecureEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return SecureContentApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class SecureContentApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProtectionConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SecureEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProtectionConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SecureEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SecureContentHostApi {
  fun configureProtection(config: ProtectionConfig)
  fun isScreenCaptured(): Boolean
  fun requestBiometricAuth(reason: String)
  fun checkIntegrity()
  fun setSensitiveClipboard(content: String, clearAfterMs: Long)
  fun clearSensitiveClipboard()

  companion object {
    /** The codec used by SecureContentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SecureContentApiPigeonCodec()
    }
    /** Sets up an instance of `SecureContentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecureContentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.configureProtection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ProtectionConfig
            val wrapped: List<Any?> = try {
              api.configureProtection(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.isScreenCaptured$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isScreenCaptured())
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.requestBiometricAuth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.requestBiometricAuth(reasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.checkIntegrity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.checkIntegrity()
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.setSensitiveClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentArg = args[0] as String
            val clearAfterMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setSensitiveClipboard(contentArg, clearAfterMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.clearSensitiveClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearSensitiveClipboard()
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SecureContentFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SecureContentFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SecureContentApiPigeonCodec()
    }
  }
  fun onEvent(eventArg: SecureEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.secure_content.SecureContentFlutterApi.onEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SecureContentApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
