// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.codenameakshay.secure_content.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SecureContentApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class ProtectionConfig (
  val enabled: Boolean,
  val protectInAppSwitcher: Boolean,
  val appSwitcherColor: Long,
  /**
   * Optional name of an image in the host app's native asset catalog to
   * center on the app-switcher / privacy overlay (rendered as a template,
   * tinted to contrast the background). When null the overlay is a plain fill.
   */
  val appSwitcherImageName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProtectionConfig {
      val enabled = pigeonVar_list[0] as Boolean
      val protectInAppSwitcher = pigeonVar_list[1] as Boolean
      val appSwitcherColor = pigeonVar_list[2] as Long
      val appSwitcherImageName = pigeonVar_list[3] as String?
      return ProtectionConfig(enabled, protectInAppSwitcher, appSwitcherColor, appSwitcherImageName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      protectInAppSwitcher,
      appSwitcherColor,
      appSwitcherImageName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProtectionConfig
    return SecureContentApiPigeonUtils.deepEquals(this.enabled, other.enabled) && SecureContentApiPigeonUtils.deepEquals(this.protectInAppSwitcher, other.protectInAppSwitcher) && SecureContentApiPigeonUtils.deepEquals(this.appSwitcherColor, other.appSwitcherColor) && SecureContentApiPigeonUtils.deepEquals(this.appSwitcherImageName, other.appSwitcherImageName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.enabled)
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.protectInAppSwitcher)
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.appSwitcherColor)
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.appSwitcherImageName)
    return result
  }
  override fun toString(): String {
    return "ProtectionConfig(enabled=$enabled, protectInAppSwitcher=$protectInAppSwitcher, appSwitcherColor=$appSwitcherColor, appSwitcherImageName=$appSwitcherImageName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SecureEvent (
  val type: String,
  val platform: String,
  val timestamp: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SecureEvent {
      val type = pigeonVar_list[0] as String
      val platform = pigeonVar_list[1] as String
      val timestamp = pigeonVar_list[2] as String?
      return SecureEvent(type, platform, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      platform,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SecureEvent
    return SecureContentApiPigeonUtils.deepEquals(this.type, other.type) && SecureContentApiPigeonUtils.deepEquals(this.platform, other.platform) && SecureContentApiPigeonUtils.deepEquals(this.timestamp, other.timestamp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.type)
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + SecureContentApiPigeonUtils.deepHash(this.timestamp)
    return result
  }
  override fun toString(): String {
    return "SecureEvent(type=$type, platform=$platform, timestamp=$timestamp)"
  }
}
private open class SecureContentApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProtectionConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SecureEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProtectionConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SecureEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SecureContentHostApi {
  fun configureProtection(config: ProtectionConfig)
  fun isScreenCaptured(): Boolean
  fun requestBiometricAuth(reason: String)
  fun checkIntegrity()
  fun setSensitiveClipboard(content: String, clearAfterMs: Long)
  fun clearSensitiveClipboard()

  companion object {
    /** The codec used by SecureContentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SecureContentApiPigeonCodec()
    }
    /** Sets up an instance of `SecureContentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecureContentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.configureProtection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ProtectionConfig
            val wrapped: List<Any?> = try {
              api.configureProtection(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.isScreenCaptured$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isScreenCaptured())
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.requestBiometricAuth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.requestBiometricAuth(reasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.checkIntegrity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.checkIntegrity()
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.setSensitiveClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentArg = args[0] as String
            val clearAfterMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setSensitiveClipboard(contentArg, clearAfterMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_content.SecureContentHostApi.clearSensitiveClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearSensitiveClipboard()
              listOf(null)
            } catch (exception: Throwable) {
              SecureContentApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SecureContentFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SecureContentFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SecureContentApiPigeonCodec()
    }
  }
  fun onEvent(eventArg: SecureEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.secure_content.SecureContentFlutterApi.onEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SecureContentApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
